name: Run E2E Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out E2E tests
        uses: actions/checkout@v2
        with:
          repository: datopian/flowershow-template-e2e

      - name: Check out Flowershow into test-app
        uses: actions/checkout@v4
        with:
          path: test-app

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies for E2E tests
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Install dependencies for template
        run: npm ci
        working-directory: test-app

      - name: Replace template /content with fixture content
        run: |
          rm -rf test-app/content
          cp -r fixtures/content test-app/content

      - name: Build the app
        run: npm run export
        working-directory: test-app

      - name: Run the tests
        run: npx playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
